language: python

python:
    - "2.5"
    - "2.6"
    - "2.7"
    - "pypy"
    - "3.2"
    - "3.3"

script:
    - python run_tests.py
    - python indent_finder.py indent_finder.py Makefile missing_file
    - python indent_finder.py --vim-output indent_finder.py && echo
