language: python

python:
    - "2.6"
    - "2.7"
    - "pypy"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "nightly"

install:
    - sudo apt-get update
    - sudo apt-get install vim-gnome
    - wget https://github.com/google/vroom/releases/download/v0.12.0/vroom_0.12.0-1_all.deb
    - sudo dpkg -i vroom_0.12.0-1_all.deb

before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

script:
    - python run_tests.py
    - python indent_finder.py indent_finder.py Makefile missing_file
    - python indent_finder.py --vim-output indent_finder.py && echo
    - vroom --verbose test.vroom
